services:
  db:
    image: "akhayat1/nhanes-postgres"
    environment:
      - CONTAINER_USER_USERNAME=test
      - CONTAINER_USER_PASSWORD=test
    ports:
      - "8787:8787"
      - "2200:22"
      - "5432:5432"

  service:
    image: "akhayat1/nhanes-patient-generator"
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db

  webapp: 
    image: "akhayat1/simpat-webapp"
    build: .
    ports:
     - "3000:3000"
    env_file:
     - .env.docker
    depends_on: 
      - service
      - db