services:
  service:
    image: "akhayat1/nhanes-patient-generator"
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
     - ${HOST_CERT_DIR}:/certs

  webapp: 
    image: "akhayat1/simpat-webapp"
    build: .
    ports:
     - "443:443"
    env_file:
     - .env.docker
    volumes:
      - "${HOST_CERT_DIR-~/.certs}:/certs"
    depends_on: 
      - service

