services:
  service:
    image: "akhayat1/nhanes-patient-generator"
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
     - ~/.certs:/certs

  webapp: 
    image: "akhayat1/simpat-webapp"
    build: .
    ports:
     - "443:443"
     - "3000:3000"
    env_file:
     - .env.docker
    volumes:
      - ~/.certs:/certs
    depends_on: 
      - service

